### ISSUE TITLE
[Feature Request] Add Boss Key functionality

### ISSUE THREAD

**Issue by patwonder** [yxl/Firefox-Muter#21]
Hit one key to hide firefox windows and mute.

好吧，其实是看到猎豹有这功能才想起来的。。。

**Comment by yxl** [comment]
在静音扩展我不想提供这个功能，不过可以提供接口让其他扩展实现这个功能，比如做到中国版中。

The Muter extension won't provider such function, but we could provide interface to let other extensions to do so.

**Comment by patwonder** [comment]
OK...
